<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Adyen extends CI_Controller {

	/**
	 * Index Page for this controller.
	 *
	 * Maps to the following URL
	 * 		http://example.com/index.php/welcome
	 *	- or -
	 * 		http://example.com/index.php/welcome/index
	 *	- or -
	 * Since this controller is set as the default controller in
	 * config/routes.php, it's displayed at http://example.com/
	 *
	 * So any other public methods not prefixed with an underscore will
	 * map to /index.php/welcome/<method_name>
	 * @see http://codeigniter.com/user_guide/general/urls.html
	 */
	public function index()
	{
		$this->load->helper(array('form','url'));
		$this->load->library('form_validation');
		$this->form_validation->set_error_delimiters('<div class="error">', '</div>');
		//Standard Functions
		$data['title'] = 'Adyen Payment';
		$data['page_view'] = 'adyen/index';

		$data['skinCode']= 'oXBk6ZMT';
		$data['merchantAccount']= 'RoomPaddyGB';
		$data['sharedSecret']= 'testHBK12';
		$data['merchantReference']= 'RoomPaddy Shops'; // Sellers Name or Company name
		$data['currencyCode']= 'GBP'; // Currency of country
		$data['shipBeforeDate']= date("Y-m-d" , mktime(date("H"), date("i"), date("s"), date("m"), date("j")+5, date("Y"))); // Shipping days
		$data['shopperLocale']= 'en_GB'; // Locale (language) to present to shopper (e.g. en_US, nl, fr, fr_BE)
		$data['orderData']= '<b>1 <i>iPod</i> MP3 Player</b>'; // A description of the payment which is displayed to shoppers
		$data['sessionValidity']= date(DATE_ATOM	, mktime(date("H")+1, date("i"), date("s"), date("m"), date("j"), date("Y"))); // example: shopper has one hour to complete
		$data['shopperEmail']= 'hardikpatel1644@gmail.com'; // the shopper's email address
		$data['shopperReference']= 'Hardik Patel';// the shopper id in our system

		$data['paymentAmount'] = '10';


		$this->load->view('layout',$data);
	}


	public function pay()
	{
		$this->load->helper(array('form','url'));
		$this->load->library('form_validation');
		$this->form_validation->set_error_delimiters('<div class="error">', '</div>');
		//Standard Functions
		$data['title'] = 'Adyen Payment';
		$data['page_view'] = 'adyen/pay';


		$paymentAmount = $_POST['paymentAmount'];
		$currencyCode = $_POST['currencyCode'];
		$shipBeforeDate = $_POST['shipBeforeDate'];
		$merchantReference = $_POST['merchantReference'];
		$skinCode = $_POST['skinCode'];
		$merchantAccount = $_POST['merchantAccount'];
		$sessionValidity = $_POST['sessionValidity'];
		$shopperEmail = $_POST['shopperEmail'];
		$shopperReference = $_POST['shopperReference'];
		$paymentAmount = $_POST['paymentAmount'];
		$sharedSecret = $_POST['sharedSecret'];
		/* ========================================================================================
		 ==================================  process fields  ====================================
		 ========================================================================================
		 $merchantSig
		 The signature in Base64 encoded format. The is generated by concatenating the values of above fields and computing HMAC over this using the shared secret
		 (the shared secret is configured in the Skin in the Adyen test backoffice)
		 $orderData
		 The $orderDataRaw which is GZIP compressed and base64 encoded
		 */
		//GZIP and base64 encode the orderData
		$orderData = base64_encode(gzencode($_POST['orderData']));

		// concatenate all the data needed to calculate the HMAC-string in the correct order
		// (please refer to Appendix B in the Integration Manual for more details)
		$hmacData = $paymentAmount . $currencyCode . $shipBeforeDate . $merchantReference . $skinCode
		. $merchantAccount . $sessionValidity . $shopperEmail . $shopperReference;

		// base64 encode the binary result of the HMAC computation. If you use a PHP version < 5.0.12 you
		// you may need to use a different HMAC implementation. Please refer to "Computing the HMAC in PHP"
		// example from the downloads section on https://support.adyen.com/
		$merchantSig = base64_encode(hash_hmac('sha1',$hmacData,$sharedSecret,true));
		echo $merchantSig;
		exit;

		$this->load->view('layout',$data);
	}
}

/* End of file welcome.php */
/* Location: ./application/controllers/welcome.php */
